### ISSUE TITLE
Save using context menu

### ISSUE THREAD

**Issue by kpinnipa** [jupytercalpoly/jupyterlab-code-snippets#107]
**Is your feature request related to a problem? Please describe.**
Save using context menu currently only works when text is highlighted. Save by highlighting is not fully functional in non-notebook files (current method is to copy text from file and paste it into the custom code snippet creator).

**Describe the solution you'd like**
1) When a cell is right-clicked and the "save as code snippet" option is selected, the cell and all of the code within the cell will be saved as a code snippet.
2) When on a non-notebook file is open, you can highlight text and save that text as a code snippet.

**Comment by jahn96** [comment]
I will start working on saving a code on a non-notebook file as a snippet.
