### ISSUE TITLE
Could you remove the keyboard short cut of Shift S？

### ISSUE THREAD

**Issue by leoliu216** [jupytercalpoly/jupyterlab-code-snippets#108]
Every time when I was writing code with a Cap-S, the extension catches it as a short cut and jump out the window for adding new snippet. It's annoying and I even cannot find where to set the shortcut. Finally, I am annoyed and uninstalled the extension.

**Comment by kpinnipa** [comment]
Thank you for reaching out to us!
We just fixed the issue and changed the shortcut from shift-s to ctrl-shift-s/cmd-shift-s so hopefully that should help resolve the problem. You can install the updated version (v1.0.3) to get the updated shortcut. Let us know if you have any other feedback, we appreciate the advice.

**Comment by leoliu216** [comment]
Thank you for solving the problem so quick. Thumb up for you !
