### ISSUE TITLE
Thoughts on saving highlighted code or cells as snippet

### ISSUE THREAD

**Issue by jahn96** [jupytercalpoly/jupyterlab-code-snippets#11]
I think we can have a `save as snippet` in context menu to save a cell as snippet if there is no highlighted code. Thoughts??

**Comment by kpinnipa** [comment]
Yep definitely an issue to be fixed. At the moment the "save snippet" option shows up when a user right clicks a cell (regardless of whether they highlighted anything or not). The reason this option was kept was to eventually allow users to have the ability to right click any cell and save all the code in cell as a snippet without requiring them to highlight all of the code.

**Comment by jahn96** [comment]
#107
