### ISSUE TITLE
Unable to build the extension after uninstall and reinstall.

### ISSUE THREAD

**Issue by leoliu216** [jupytercalpoly/jupyterlab-code-snippets#114]
Hello, last time I reported the problem of shortcut as Cap-S and I uninstalled the extension. 

After that, you claim to have fixed the problem so I wanted  to reinstall the extension. But I failed to build it or use it in the jupyterlab again. I enabled the extension, tried the command of clean and rebuild, but failed to activate the extension whatever measures do I take. 

Could you help me with solving the problem or check if it is the problem of the extension?
![image](https://user-images.githubusercontent.com/48639456/91998515-ec644a80-ed00-11ea-83ea-99b40d1a4877.png)

**Comment by jahn96** [comment]
@leoliu216 Thanks for the interests again!

Have you deleted the extension with `jupyter labextension uninstall jupyterlab-code-snippets` and reinstalled it again with `jupyter labextension install jupyterlab-code-snippets`?

**Comment by leoliu216** [comment]
> @leoliu216 Thanks for your interest again!
> 
> Have you deleted the extension with `jupyter labextension uninstall jupyterlab-code-snippets` and reinstalled it again with `jupyter labextension install jupyterlab-code-snippets`?

Yes. I did the deletion and re-installation with the right code. The problem is solved just now by deleting the build_config.json file in the path "...\jupyter\lab\settings". ( The full path is "C:\Users\84955\anaconda3\share\jupyter\lab\settings" for Jupyter lab installed on my computer).

The build_config.json file recorded the uninstalled package, which, in my opinion, caused the issue I initiated. Maybe you can add some work in the extension to scan the  build_config.json file automatically and delete the "jupyterlab-code-snippets" after installation. 

![image](https://user-images.githubusercontent.com/48639456/92034770-539af280-ed33-11ea-8873-6ddb66e3abd0.png)

**Comment by leoliu216** [comment]
By the way, the new shortcut does not work again as the ctrl-shift-s is already set as the shortcut for save as in jupyter lab. Is there a way for setting it by user?

![image](https://user-images.githubusercontent.com/48639456/92037696-c4dca480-ed37-11ea-8537-59f92d0d074f.png)

**Comment by jahn96** [comment]
The new shortcut should work when there is a focus on the cell. If you want to change the keyboard shortcut, you can go to Settings -> Advanced Settings editor -> keyboard shortcut. There is a video description on how in this link: [JupyterLab Documentation](https://jupyterlab.readthedocs.io/en/stable/user/interface.html). 

Unfortunately, the new shortcut to create a new snippet is NOT user-configurable currently.

**Comment by jahn96** [comment]
#133 Started to discuss about shortcut issue here
