### ISSUE TITLE
Boot jupyter lab in other directory will lose original records. 

### ISSUE THREAD

**Issue by CNFeffery** [jupytercalpoly/jupyterlab-code-snippets#115]
I just created several snippets in `jupyter lab`，but when I boot `jupyter lab` in other directory, I can't find original snippets records🤔.

**left**: original work directory, **right**: another work directory but under the same conda enviroment.
![image](https://user-images.githubusercontent.com/49147660/92357244-1612dc80-f11a-11ea-9646-38723b9ca955.png)

**Comment by jahn96** [comment]
Hi
Thanks for creating an issue! #121  That's one of the issues that we are planning to fix. Thanks!
