### ISSUE TITLE
UI/UX: Changing/updating snippet names

### ISSUE THREAD

**Issue by aivydang** [jupytercalpoly/jupyterlab-code-snippets#122]
**Question: How can we make it easier to rename snippets?**

_Current task flow:_
- User browses snippets > clicks "..." button > chooses "edit snippet" > edits snippet in a separate file > saves/updates snippet

_Ideation:_
- right click or double click the snippet to change it

_Things to keep in mind:_
- Would this still open into the editor?
- What would it look like in the snippet panel?

**Comment by jahn96** [comment]
@aivydang could you look at the linked PR and tell me how you think about its design? Thanks! :)
