### ISSUE TITLE
Error: empty user input!

### ISSUE THREAD

**Issue by jahn96** [jupytercalpoly/jupyterlab-code-snippets#13]
Should all the input fields for code snippet be required?

**Comment by jahn96** [comment]
Also, we should limit invalid languages in jupyterlab.

**Comment by kpinnipa** [comment]
Yeah for languages, I was thinking about maybe switching to a dropdown that lists the languages that jupyterlab supports. As of right now I made them all required but I think the main ones that need to be required are the name and language, description could be made optional.
