### ISSUE TITLE
Question about shortcut

### ISSUE THREAD

**Issue by jahn96** [jupytercalpoly/jupyterlab-code-snippets#133]
1. Customizing the keyboard shortcut on JupyterLab seems to just add a new shortcut instead of replacing it.
2. Currently, the shortcut to save as snippet is `Accel Shift S`. And, this overrides `Save AS..` shortcut, and this is a problem especially in non-notebook file because there's no way to get around it unlike notebook.

**Comment by kpinnipa** [comment]
Definitely an issue then, would it be better to review the list of taken shortcuts and then try to find a shortcut path that hasn't been taken? Unfortunately we may not be able to use a shortcut that goes well with the phrase "save as code snippet" but at least we won't have to worry about overwriting other commands.

**Comment by jahn96** [comment]
Changed the shortcut to `Access Shift A`
