### ISSUE TITLE
Prepare for JupyterLab 3.0 version update

### ISSUE THREAD

**Issue by jahn96** [jupytercalpoly/jupyterlab-code-snippets#145]
## Purpose:  Update code snippets extension to be compatible with JupyterLab 3.0 release.

Tasks:
- Require Node v12
- Use update script
- Fix encountered bugs

**Comment by dhendry** [comment]
This is one of my favourite extensions. Would love to see it continue to be maintained and updated for JupyterLab 3.0!

Thanks a lot for the great work!
