### ISSUE TITLE
Filter tag not seen to enable filters of the snippets

### ISSUE THREAD

**Issue by rahulmadanraju** [jupytercalpoly/jupyterlab-code-snippets#149]
**Describe the bug**
A clear and concise description of what the bug is:
The filters are not seen in the 'add-snippet' bar. 

**Expected behavior**
I want to filter the tags, but I don't see the option to filter them. Moreover, I don't have the tag option provided when I try to save the snippet from Jupyter lab.

**Screenshots**
- added
![image](https://user-images.githubusercontent.com/38735728/98244038-13dccb00-1f6f-11eb-9307-06ac1b7e0169.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge 
 - Version:86.0.622.61

**Comment by jahn96** [comment]
Hi,
What version of code snippet extension are you using currently?

**Comment by rahulmadanraju** [comment]
It is v0.1.1.. the above versions aren't  supportive to juyterlab version less than 2.2. Can the filter tags be added to the version 0.1.1? Such that it can be used? 

I did try with tag key within the json file. But not quite sure of it reflecting at the frontend.

**Comment by jahn96** [comment]
Hi,

Sorry for the inconvenience.
We are trying to have our extension along with the latest JupyterLab. So, you have to upgrade your jupyterlab to use all the functionalities in our extension.

Thanks!
