### ISSUE TITLE
inconvenient input format...

### ISSUE THREAD

**Issue by epsilon-deltta** [jupytercalpoly/jupyterlab-code-snippets#154]
**Is your feature request related to a problem? Please describe.**
when i register new snippet, i 'm so inconvenient to fill a form exactly....
> i dont like filling describing form,language (can allow blank form)
> i hope it supports upper cases in title
#### #thank you (~~in personally , i like this extension so much .~~)

**Comment by jahn96** [comment]
Hi, 

Thank you for creating an issue for code snippet extension.
We will reflect the issue in the next development cycle.

Thanks!
