### ISSUE TITLE
Cannot install with JupyterLab 3.0.1

### ISSUE THREAD

**Issue by samesand** [jupytercalpoly/jupyterlab-code-snippets#158]
When trying to pip install with 3.0.1 it gives me the following error:
Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.0.0 <3.1.0          >=2.1.2 <3.0.0 @jupyterlab/application
>=3.0.0 <3.1.0          >=2.2.4 <3.0.0 @jupyterlab/apputils
>=5.0.0 <5.1.0          >=4.1.0 <5.0.0 @jupyterlab/coreutils
>=3.0.0 <3.1.0          >=2.1.2 <3.0.0 @jupyterlab/docmanager
>=3.0.0 <3.1.0          >=2.1.2 <3.0.0 @jupyterlab/fileeditor
>=3.0.0 <3.1.0          >=2.1.2 <3.0.0 @jupyterlab/notebook
>=3.0.0 <3.1.0          >=2.1.1 <3.0.0 @jupyterlab/rendermime
>=6.0.0 <6.1.0          >=5.0.0 <6.0.0 @jupyterlab/services

**Comment by s-rog** [comment]
I'm guessing the updates (for jupyterlab 3) haven't been pushed to the release channel yet.
The changes were only merged to master 6 hours ago.

**Comment by jahn96** [comment]
Yes, we are planning to release our updates tomorrow.
Thank you so much!

**Comment by samesand** [comment]
Thank you!
