### ISSUE TITLE
duplicate snippet name error - json already exists

### ISSUE THREAD

**Issue by bala-srm** [jupytercalpoly/jupyterlab-code-snippets#164]
**Describe the bug**

**To Reproduce**

**Expected behavior**
When I create a snippet and click on "create & Save' I get the error mentioned in subject line. There is no other snippet saved by the same name. In fact, whatever you change the snippet name to , the same error is repeated.

**Screenshots**
![image](https://user-images.githubusercontent.com/53083124/106933366-d2f77c80-673e-11eb-9fa0-44ef530a29d9.png)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser Chrome

**Additional context**

**Comment by kpinnipa** [comment]
Thank you for reporting the error! We are currently working on patching the issue and will update the extension when the problem is fixed.
