### ISSUE TITLE
Download snippets to share

### ISSUE THREAD

**Issue by jahn96** [jupytercalpoly/jupyterlab-code-snippets#179]
We would like to add an option to download snippets to share with different people as the snippets would be stored in settings API in the next release.

**Comment by Dombo** [comment]
I think the ability to specify the location of the snippets directory would get this enhancement most of the way there. For context I run a multi user jupyterhub installation and would love to share snippets across users in the installation.

To work around this I've put a shared volume in the jupyterhub configuration where the snippets dir would usually be created, this let's my team share snippets amongst one another - great for code reuse.

Now all that's missing are links for specific snippets :+1:
