### ISSUE TITLE
The Snippet preview (on the side) is too small

### ISSUE THREAD

**Issue by Zawarud** [jupytercalpoly/jupyterlab-code-snippets#189]
This is how look : 
![immagine](https://user-images.githubusercontent.com/53933533/115662437-43299d80-a33f-11eb-8a44-a38a1f227098.png)

I can change this in the setting? How?

**Comment by kpinnipa** [comment]
Hi Zawarud, at the moment the size of the snippet is not user-configurable. Could you tell me a little bit about why you want the preview to be bigger? Our initial through process when creating the preview was for it to just show a the general shape of the code, but we're always looking to improve things and your feedback would be helpful!

**Comment by Zawarud** [comment]
For see the code. In the case i have similar code snippet.
A question : Van I add this code in a cell line without create another One?

**Comment by kpinnipa** [comment]
Got it, thank you for the feedback! At the moment the size of the preview will stay fixed and just provide a small preview of the basic outline of the code structure however there is an option to see the full snippet by clicking the 3 dots on the righthand side and selecting edit snippet.

In regards to your question, can you tell me a little bit more about what you mean by adding code without creating another one? Are you referring to creating another snippet or creating a new cell in the notebook?

**Comment by Zawarud** [comment]
> 
> 
>
> 
> In regards to your question, can you tell me a little bit more about what you mean by adding code without creating another one? Are you referring to creating another snippet or creating a new cell in the notebook or something else?

Without creating another cell each time, but add the code in the selected line.

**Comment by kpinnipa** [comment]
Got it, yes that is possible! After placing your cursor in an existing cell (where you want to paste), on the desired code snippet click on the three dots and select "Insert snippet" and the line of code will be inserted into the existing cell within a notebook without creating a new cell.

<img width="735" alt="Screen Shot 2021-04-27 at 12 21 31 PM" src="https://user-images.githubusercontent.com/49247883/116299928-20d6bc00-a753-11eb-851c-86cd522eb141.png">

<img width="824" alt="Screen Shot 2021-04-27 at 12 22 07 PM" src="https://user-images.githubusercontent.com/49247883/116299992-33e98c00-a753-11eb-80ad-42bc49f6b8f1.png">

**Comment by jahn96** [comment]
@Zawarud 
Hi, we just made the font size configurable in JupyterLab Advanced Settings. We will release the update next week once we fix the security vulnerability issue. Please refer to #201 for details.
