### ISSUE TITLE
Question - possible to add a value to the Snippets 'Language' list - would like to add Powershell

### ISSUE THREAD

**Issue by Daksol** [jupytercalpoly/jupyterlab-code-snippets#221]
Is there a way to add a value to the Language dropdown? I wanted to add Powershell.

Current values are:

> Agda, Aldor, Babel, C, C#, C++, Clojure, Clojurescript, Coconut, CoffeeScript, Common Lisp, Cryptol, Erlang, F#, Forth, Fortran, Galileo, Gfm, Go, Groovy, Guile, Haskell, HiveQL, Hy, Java, JavaScript, Julia, Kotlin, LiveScript, Lua, Matlab, Maxima, NodeJS, OCaml, Octave, PARI/GP, PHP, Perl, Pike, Processing, Prolog, PureScript, Python, Q, Q#, R, Racekt, Rascal, Ruby, Rust, SAS, SQL, Scala, Scheme, Scilab, Singular, Stata, TaQL, TypeScript, Xonsh, bash, sbt, zsh

Thanks

**Comment by meshaun9** [comment]
Any update here? I'm also interested in seeing if we can add Markdown in the language list?

**Comment by jahn96** [comment]
Just published a new version with those two languages.
