### ISSUE TITLE
the extension could not be installed

### ISSUE THREAD

**Issue by Betristor** [jupytercalpoly/jupyterlab-code-snippets#228]
**Describe the bug**
The extension could not be installed.

**To Reproduce**
1. Go to extension file folder
2. run ```npm install```
3. the conflict of npm packages is shown

**Expected behavior**
code-snippets extension is successfully built.

**Screenshots**
<img width="284" alt="image" src="https://user-images.githubusercontent.com/55777837/161018570-0d9a350a-b11c-4269-ac70-893f4e3a752d.png">
<img width="796" alt="image" src="https://user-images.githubusercontent.com/55777837/161018759-b1b0cce8-5698-4ecd-8b47-024e94d04e64.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.3
 - Browser chrome

**Additional context**
Log from npm
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: jupyterlab-code-snippets@2.1.0
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.5.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0 || ^6.0.0" from @typescript-eslint/parser@2.34.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"^2.27.0" from the root project
npm ERR!   peer @typescript-eslint/parser@"^2.0.0" from @typescript-eslint/eslint-plugin@2.34.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     dev @typescript-eslint/eslint-plugin@"^2.27.0" from the root project
```

**Comment by grisuthedragon** [comment]
The same on various Linux installations of Jupyterlab.

**Comment by psychemedia** [comment]
@hhhuang18 Looking at the system defaults snippet, the `id` attribute of the first snippet is missing, which may be the problem?

The attribute does appear in the definition file in the codebase (eg https://github.com/jupytercalpoly/jupyterlab-code-snippets/blob/5713c63aad30f4adeea99f1bddb26646f020d05b/schema/snippets.json#L45 ) but not in the system default file when the extension is installed:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/82988/180412103-7506ef12-006d-46ce-9235-8544cc3994c3.png">

**Comment by dcervenkov** [comment]
@psychemedia, adding `"id": 0,` to the first snippet indeed fixes the issue. Well spotted!
